package:
    name: cpptraj
    version: "2016.0.07"

source:
    git_url: https://github.com/Amber-MD/cpptraj.git     [unix]
    git_tag: 28982fda768b6b378fd4ce500fc7a4709ebdb98d    [unix]
    url: https://ci.appveyor.com/api/buildjobs/30y4hbfv1nk4dwty/artifacts/cpptraj-2252910.zip [win]
    fn: cpptraj-2252910.zip [win]


build:
  number: 0
  skip:
    - [not unix]

requirements:
  build:
    - libnetcdf
    - arpack
    - bzip2
    - openblas [linux]
    - gcc

  run:
    - libnetcdf
    - arpack
    - bzip2
    - openblas [linux]
    - libgcc

test:
  commands:
    - cpptraj -h

about:
  home: https://github.com/amber-md/cpptraj
  license: GPLv3+
  summary: 'Biomolecular simulation trajectory/data analysis.'
