package:
  name: boost
  version: 1.59.0

source:
   url: http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.bz2
   fn: boost_1_59_0.tar.bz2
   md5: 6aa9a5c6a4ca1016edd0ed1178e3cb87

build:
  number: 0
  skip:
    - [win]

requirements:
  build:
    - python
    - bzip2
    - zlib

  run:
    # this includes boost.python which is linked against libpython.
    # so we need to make sure we create a different conda binary to
    # go along with different versions of python.
    - python
    - bzip2
    - zlib

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: "Boost provides free peer-reviewed portable C++ source libraries."

